---
# tasks file for hostr.caclient
- name: Install pip3
  apt:
    pkg:
      - python3-pip
      - python3-cryptography

# - name: Install cryptography python package, necessary to generate certificates with ansible
#   ansible.builtin.pip:
#     name: cryptography  

- name: Install OpenSSL
  package:
    name: openssl
    state: present

- name: Create directory for client certificates
  file:
    path: "/etc/ssl/client"
    state: directory
    mode: "0700"

- name: Generate private key for client
  openssl_privatekey:
    path: "/etc/ssl/client/{{ inventory_hostname }}.key"
    size: 2048
  register: client_private_key

- name: Generate CSR for client
  openssl_csr:
    path: "/etc/ssl/client/{{ inventory_hostname }}.csr"
    privatekey_path: "{{ client_private_key.filename }}"
    common_name: "{{ inventory_hostname }}"
    country_name: "{{ ca_country_code }}"
    state_or_province_name: "{{ ca_state }}"
    locality_name: "{{ ca_city }}"
    organization_name: "{{ ca_organization_name }}"
    email_address: "{{ ca_email_address }}"
  register: client_csr
