---
# vars file for proxmox.cars.be
# this vars file has the role of an inventory, i.e. all machines defined in this vars
# file will be setup on Proxmox and used by the subsequent roles to setup webservers, caches, databases, etc.
proxmox_vms:
 - ip: 192.168.1.60
   id: 600
   group:
    - "webserver"
 - ip: 192.168.1.61
   id: 601
   group:
    - "redis"
 - ip: 192.168.1.62
   id: 602
   group:
    - "database"
 - ip: 192.168.1.63
   id: 603
   group:
    - "identity_server"
 - ip: 192.168.1.64
   id: 604
   group:
    - "http_api"
 - ip: 192.168.1.68
   id: 608
   group:
    - "http_api"     
 - ip: 192.168.1.69
   id: 609
   group:
    - "http_api"     
 - ip: 192.168.1.65
   id: 605
   group:
    - "grafana"
 - ip: 192.168.1.66
   id: 606
    - "prometheus"
 - ip: 192.168.1.67
   id: 607
   group:
    - "otlp_controller"
