---
# vars file for proxmox.cars.be
# this vars file has the role of an inventory, i.e. all machines defined in this vars
# file will be setup on Proxmox and used by the subsequent roles to setup webservers, caches, databases, etc.
proxmox_vms:
 - ip: 192.168.1.60
   id: 600
   group:
    - "webserver"
 - ip: 192.168.1.61
   id: 601
   group:
    - "redis"
 - ip: 192.168.1.62
   id: 602
   group:
    - "database"
 - ip: 192.168.1.63
   id: 603
   group:
     - "identity_server"
 - ip: 192.168.1.64
   id: 604
   group:
     - "http_api"
