---
- name: Deploy the ABP REST API
  hosts: http_api
  #become: yes
  remote_user: root
  roles:
     - { role: ppst0.dotnet, dotnet_package: "{{ dotnet_sdk }}" }     
     - hostr.abprestapi 