- name: Azure Ubuntu Azure VM playbook
  hosts: localhost
  # Azure credentials are stored under user bart, so become bart
  become: yes
  become_user: bart
  remote_user: root
  vars_files:
    - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    # - name: "instances_number"
    #   prompt: "Choose a number of virtual machines to create"
    #   private: no
    #   default: 1    
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: no
      default: ansible
    - name: project_location
      prompt: "The Azure VM location"
      private: no
      default: westeurope
    - name: vm_os_offer
      prompt: "The VM OS offer, for instance UbuntuServer"
      private: no
      #default: UbuntuServer
      default: RHEL
    - name: vm_os_publisher
      prompt: "The VM OS publisher, for instance Canonical"
      private: no
      #default: Canonical
      default: RedHat
    - name: vm_os_sku
      prompt: "The SKU of the OS, for instance 18.04-LTS"
      private: no
      #default: 18.04-LTS
      #BYOS
      #default: 9-lvm-gen2
      #gold image
      default: 91-gen2
    - name: vm_size
      prompt: "The VM size, check https://docs.microsoft.com/en-us/azure/virtual-machines/sizes for a full list"
      private: no
      #default: Standard_A4_v2
      default: Standard_B2s
  roles:
    - azure_ubuntu_vm
    - azure_matrix    
    # - { role: docker, ips: output_ip_address.results }
- import_playbook: "/home/bart/justsec/matrix-docker-ansible-deploy/setup.yml" 
  #vars:
    #target: 52.236.166.81
    #ansible_host: 52.236.166.81 
    #ansible_ssh_user: "root" 
    #ansible_connection: "local" 
    #ansible_python_interpreter: "/usr/bin/python3"