- name: "grafana setup playbook"
  hosts: grafana
  remote_user: root
  vars_files:
    # - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_NAME') }}"
    - name: webserver_public_repo
      prompt: "Enter the git remote URL."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GIT_WEBSITE_REPO') }}"  
    - name: grafana_install_folder
      prompt: "Enter the installation folder of Prometheus."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GRAFANA_INSTALL_FOLDER') }}"    
  module_defaults:
    group/community.grafana.grafana:
      grafana_url: "http://{{ groups['grafana'][0] }}:3000"
      #api user
      grafana_user: "admin"
      #todo move to settings
      grafana_password: "admin"      
  # based on https://citizix.com/how-to-install-and-set-up-grafana-in-ubuntu-20-04-using-ansible/
  tasks:    
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install dependencies
      apt:
        pkg:
          - gnupg          
          - curl
          - wget
          - software-properties-common
        state: latest
        update_cache: yes
    - name: add grafana gpg key - repo is not trusted, add trusted=yes
      ansible.builtin.shell: |
        apt-get install -y apt-transport-https software-properties-common wget
        mkdir -p /etc/apt/keyrings/
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg trusted=yes] https://apt.grafana.com stable main" | tee -a /etc/apt/sources.list.d/grafana.list
        apt-get update
    - name: Install the grafana package
      apt:
        name: grafana
        state: present
        update_cache: yes
      notify:
        - Start grafana
        - Enable grafana
    - name: Create or update a Grafana user, in this case the default admin
      community.grafana.grafana_user:
        name: "Default admin"
        email: "admin@cars.be"
        #grafana user
        login: "admin"
        #cannot be edited
        #todo move to settings
        password: "admin"
        is_admin: true   
        state: present     
    - name: Create or update a Grafana user, in this case the default user
      community.grafana.grafana_user:
        name: "Default user"
        email: "bart@cars.be"
        #grafana user
        #todo allow to add users in bulk
        login: "bart"
        #cannot be edited
        #todo move to settings
        password: "bart"
        is_admin: true   
        state: present
    - name: create prometheus datasource
      community.grafana.grafana_datasource:
        name: prometheus
        ds_type: prometheus
        #todo curl 'http://192.168.1.66:9090/api/v1/query?query=up&time=2015-07-01T20:10:51.781Z'
        #do not include the /metrics
        ds_url: http://192.168.1.66:9090/
        #access: proxy
        tls_skip_verify: true
        uid: prometheus
        # additional_json_data:
        #   httpHeaderName1: "Authorization"
        # additional_secure_json_data:
        #   httpHeaderValue1: "Bearer ihavenogroot"        
    - name: Import Grafana dashboard https://github.com/dotnet/aspire/tree/main/src/Grafana
      community.grafana.grafana_dashboard:        
        #TODO first create this folder, now dashboard is in general
        #folder: dotnet
        #https://grafana.com/grafana/dashboards/19924-asp-net-core/
        #dashboard_id: 19924
        #dashboard_revision: 1        
        path: "{{ playbook_dir }}/19924_rev4.json"
        state: present
        overwrite: true
        #dashboard_url: https://grafana.com/api/dashboards/19924/revisions/4/download
    - name: Import Grafana dashboard https://github.com/dotnet/aspire/tree/main/src/Grafana
      community.grafana.grafana_dashboard:        
        #TODO first create this folder, now dashboard is in general
        #folder: dotnet
        #https://grafana.com/grafana/dashboards/19924-asp-net-core/
        #dashboard_id: 19925
        #dashboard_revision: 1             
        #path: /19925_rev3.json
        dashboard_url: https://grafana.com/api/dashboards/19925/revisions/3/download
  handlers:
    - name: Start grafana
      systemd:
        name: grafana-server
        state: started
    - name: Enable grafana
      systemd:
        name: grafana-server
        enabled: yes