# inspired by https://stackoverflow.com/questions/30226113/ansible-ssh-prompt-known-hosts-issue
- name: "Configure the known_hosts file after init of the VMs/Containers on Azure, Proxmox, etc."
  hosts: localhost
  connection: local
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"

  tasks:
    - name: For each host, remove the host from the '{{ ssh_known_hosts }}'
      #shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
      shell: "ssh-keygen -R {{ item }}"
      with_items: "{{ ssh_known_hosts }}"
      register: ssh_known_host_results
      ignore_errors: True

    - name: Add/update the public key of all servers in the '{{ ssh_known_hosts }}'
    #ssh-keyscan writes to stderr, so we redirect it to /dev/null
      ansible.builtin.shell: |  
        ssh-keyscan -H -t ed25519 -T 15 {{ item }} 2> /dev/null >> ~/.ssh/known_hosts
      register: ssh_keyscan_result
      retries: 5
      delay: 5
      until: ssh_keyscan_result.rc == 0
      with_items:  "{{ ssh_known_hosts }}"
      ignore_errors: True

- name: Add github.com to all relevant machines from the inventory
  hosts: webserver:identity_server:http_api
  remote_user: root

  tasks:
  - name: Update known hosts
    #ssh-keyscan writes to stderr, so we redirect it to /dev/null
    ansible.builtin.shell: |  
      ssh-keyscan -H -t ed25519 -T 15 github.com 2> /dev/null >> ~/.ssh/known_hosts
    register: ssh_keyscan_result
    retries: 5
    delay: 5
    until: ssh_keyscan_result.rc == 0    
    ignore_errors: True    