- name: Deploy the NGINX Servers
  hosts: proxy
  #become: yes
  remote_user: root
  vars:
    # example variables to enable/disable roles
    proxy_a_feature_enabled: true
    ssl_certificate: /etc/ssl/certs/nginx-selfsigned.crt
    ssl_certificate_key: /etc/ssl/private/nginx-selfsigned.key
  vars_files:
    # - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_NAME') }}"    
    - name: project_domain
      prompt: "The project domain name, for example cars.be"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_DOMAIN') }}"   
  roles:
    - geerlingguy.certbot
    - hostr.nginx