- name: Deploy the NGINX Servers
  hosts: proxy
  #become: yes
  remote_user: root
  vars:
    # TBD
    proxy_lets_encrypt_enabled: false
    # ssl_certificate: /etc/ssl/certs/nginx-selfsigned.crt
    # ssl_certificate_key: /etc/ssl/private/nginx-selfsigned.key
    ssl_certificate: "/etc/ssl/client/certificate.pem"
    ssl_certificate_key: "/etc/ssl/client/{{ ansible_host }}.key"
    ssl_certificate_pkcs12: "/etc/ssl/client/server.p12"
  vars_files:  
    # - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_NAME') }}"    
    - name: project_domain
      prompt: "The project domain name, for example cars.be"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_DOMAIN') }}"   
    - name: client_private_key_passphrase
      prompt: "Your client private key passphrase"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CLIENT_PRIVATE_KEY_PASSPHRASE')}}"           
  roles:
    - geerlingguy.certbot
    - hostr.nginx