- name: "prometheus setup playbook"
  hosts: prometheus
  remote_user: root
  vars_files:
    # - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_NAME') }}"
    - name: webserver_public_repo
      prompt: "Enter the git remote URL."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GIT_WEBSITE_REPO') }}"  
    - name: prometheus_install_folder
      prompt: "Enter the installation folder of Prometheus."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROMETHEUS_INSTALL_FOLDER') }}"    
  roles:
    - role: prometheus.prometheus.prometheus  
      vars:
        prometheus_scrape_configs: [
                                        {
                                            "job_name": "prometheus",
                                            "metrics_path": "{{ prometheus_metrics_path }}",
                                            "static_configs": [
                                                {
                                                    "targets": [
                                                        "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
                                                    ]
                                                }
                                            ]
                                        },
                                       {
                                            "job_name": "cars.be",
                                            "metrics_path": "{{ prometheus_metrics_path }}",
                                            "static_configs": [
                                                {
                                                    "targets": [
                                                        "{{ groups['webserver'][0] }}:5000"
                                                    ]
                                                }
                                            ]
                                        },
                                    ]
  tasks:    
    - name: Install dependencies
      apt:
        pkg:
          - gnupg
        state: latest
        update_cache: yes
    - name: Update repository
      apt_repository:
        repo: 'ppa:git-core/ppa'
        state: present
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
    # - name: Copy prometheus.yml
    #   template:
    #     src: prometheus.yml.j2
    #     dest: "{{ prometheus_install_folder }}/prometheus.yml"
    #     owner: root
    #     group: root
    #     mode: 0644
    # - name: reload systemctl
    #   command: systemctl daemon-reload
    # - name: Make sure a service unit is running
    #   ansible.builtin.systemd_service:
    #     #start after reboot
    #     enabled: true
    #     #restart now so we don't have to reboot the machine
    #     #restart and not start: if we were running before the daemon-reload, we have to restart to get the new config
    #     state: restarted
    #     name: webserver_blazor