---
- name: Prompt for all variables.  
#TBD order vars in blocks
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_NAME') }}"
    - name: ca_name
      prompt: "Your CA name"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_NAME') }}"
    - name: ca_country_code
      prompt: "Your CA country code"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_COUNTRY_CODE') }}"
    - name: ca_state
      prompt: "Your CA state"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_STATE') }}"
    - name: ca_city
      prompt: "Your CA city"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_CITY') }}"
    - name: ca_organization_name
      prompt: "Your CA organization name"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_ORGANIZATION_NAME') }}"
    - name: ca_email_address
      prompt: "Your CA email address"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_EMAIL_ADDRESS') }}"
    - name: ca_pass
      prompt: "Your CA passphrase"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CA_PASSPHRASE')}}"
    - name: client_private_key_passpharse
      prompt: "Your client private key passphrase"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'CLIENT_PRIVATE_KEY_PASSPHRASE')}}"         
    - name: redis_password
      prompt: "Enter the Redis password for the legacy authentication."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'REDIS_PASSWORD') }}"
    - name: redis_network_port
      prompt: "Enter the Redis port."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'REDIS_PORT') }}"
    - name: redis_network_interface
      prompt: "Enter the Redis network interface to listen on."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'REDIS_NETWORK_INTERFACE') }}"           
    - name: webserver_public_repo
      prompt: "Enter the git remote URL."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GIT_WEBSITE_REPO') }}"  
    - name: prometheus_install_folder
      prompt: "Enter the installation folder of Prometheus."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROMETHEUS_INSTALL_FOLDER') }}"         
    - name: influxdb_username
      prompt: "The InfluxDB database user name."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'INFLUXDB_DATABASE_USERNAME') }}"   
    - name: influxdb_password
      prompt: "The InfluxDB database password."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'INFLUXDB_DATABASE_PASSWORD') }}"               
    - name: influxdb_database_name
      prompt: "The InfluxDB database name to setup."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'INFLUXDB_DATABASE_NAME') }}"
    - name: grafana_install_folder
      prompt: "Enter the installation folder of Prometheus."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GRAFANA_INSTALL_FOLDER') }}"  
    - name: database_password
      prompt: "Enter the password."      
      private: false
      default: "{{ lookup('ansible.builtin.env', 'SQL_SERVER_PASSWORD') }}"  
    - name: webserver_install_folder
      prompt: "Enter the install folder of the webapp."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'WEBSERVER_INSTALL_FOLDER') }}"
    - name: asp_net_core_environment
      prompt: "Enter the asp net core environment (Development, Acceptance or Production)"  
      private: false
      default: "{{ lookup('ansible.builtin.env', 'ASP_NET_CORE_ENVIRONMENT' ) }}"
    - name: dotnet_sdk
      prompt: "The dotnet SDK version."  
      private: false
      default: "dotnet-sdk-8.0"
    - name: abp_project_name
      prompt: The name of the ABP project, this is the name of the project you used in 'abp new Acme.BookStore -csf'
      private: false
      default: "{{ lookup('ansible.builtin.env', 'SOLUTION_NAME' ) }}"
    - name: openiddict_application_identifier
      prompt: Part of the key used to identify OpenIddict applications in the appsettings, used during db identityserver.appsettings.json.j2
      private: false
      default: "{{ lookup('ansible.builtin.env', 'OPENIDDICT_APPLICATION_IDENTIFIER' ) }}"
    - name: project_domain
      prompt: "The project domain name, for example cars.be"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROJECT_DOMAIN') }}"
    - name: http_api_public_repo
      prompt: "Enter the git remote URL."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GIT_WEBSITE_REPO') }}"  
    - name: http_api_install_folder
      prompt: "Enter the install folder of the webapp."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'WEBSERVER_INSTALL_FOLDER') }}"  
    - name: identityserver_public_repo
      prompt: "Enter the git remote URL."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'GIT_WEBSITE_REPO') }}"  
    - name: identityserver_install_folder
      prompt: "Enter the install folder of the identity server."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'WEBSERVER_INSTALL_FOLDER') }}"