- name: "Proxmox Ubuntu VM playbook"    
  hosts: localhost
  remote_user: root
  vars_files:
    # - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_PROJECT_NAME') }}"      
    - name: proxmox_ip_address
      prompt: "The proxmox IP address"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_PUBLIC_IP') }}"
    - name: proxmox_api_token
      prompt: "The proxmox API token with sufficient rights to install, stop and remove VMs."
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_API_SECRET') }}"
    - name: proxmox_node
      prompt: "The proxmox node to install our VM(s) on."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_NODE') }}"
    - name: proxmox_api_user
      prompt: "The proxmox API user with sufficient rights to install, stop and remove VMs."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_API_USER') }}"
    - name: proxmox_api_token_id
      prompt: "The proxmox API token id with sufficient rights to install, stop and remove VMs."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_API_TOKEN') }}"
    - name: proxmox_local_storage
      prompt: "The name of the local storage used for the storage of your VMs"
      private: false
      default: "{{ lookup('ansible.builtin.env', 'PROXMOX_LOCAL_STORAGE') }}"
  roles:
    - hostr.proxmox
  vars:
    ansible_ssh_user: root
