- name: "Redis setup playbook"
  hosts: redis
  remote_user: root
  vars_files:
    # - azure_ubuntu_vm/vars/main.yml
  vars_prompt:
    - name: project_name
      prompt: "The project name which will be used to initialize resource group names, vms, nics, etc."
      private: false
      default: ansible
    - name: redis_password
      prompt: "Enter the Redis password for the legacy authentication."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'REDIS_PASSWORD') }}"
    - name: redis_network_port
      prompt: "Enter the Redis port."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'REDIS_PORT') }}"
    - name: redis_network_interface
      prompt: "Enter the Redis network interface to listen on."
      private: false
      default: "{{ lookup('ansible.builtin.env', 'REDIS_NETWORK_INTERFACE') }}"      
  roles:
    - role: geerlingguy.redis
      redis_port: "{{ redis_network_port }}"
      redis_bind_interface: "{{ redis_network_interface }}"
      redis_requirepass: "{{ redis_password }}"
      # TODO double check: ABP needs some of the commands
      # redis_disabled_commands:
      #   - FLUSHDB
      #   - FLUSHALL
      #   - KEYS
      #   - PEXPIRE
      #   - DEL
      #   - CONFIG
      #   - SHUTDOWN
  vars:
    ansible_ssh_user: root
