---
roles:
  # to install redis
  - name: geerlingguy.redis
    type: galaxy
    source: https://github.com/geerlingguy/ansible-role-redis
  # to install dotnet    
  - name: ppst0.dotnet
    type: galaxy
    source: https://github.com/ppst0/ansible-role-dotnet

collections:  
  - prometheus.prometheus  
  - grafana.grafana
  - community.crypto  